name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      kicad_version:
        description: "KiCad Version"
        required: true
        default: "9.0"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write # Required to push to GitHub Container Registry (ghcr.io)
      contents: read

    env:
      KICAD_VERSION: "9.0"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            --build-arg KICAD_VERSION=${{ inputs.kicad_version }} \
            -t ghcr.io/${{ github.repository_owner }}/kicad:latest \
            -t ghcr.io/${{ github.repository_owner }}/kicad:${{ inputs.kicad_version }} \
            -f DOCKERFILE-9.0-stable .

      - name: Push Docker images to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/kicad:latest
          docker push ghcr.io/${{ github.repository_owner }}/kicad:${{ inputs.kicad_version }}
